import fs from 'fs';
import path from 'path';

// Auto-generated by extract-content.js
// Components: AboutA, AboutB, AboutC, Header, Footer

export async function load() {
	const contentDir = path.join(process.cwd(), 'static', 'content');

	try {
		return {
			content: {
		AboutA: JSON.parse(fs.readFileSync(path.join(contentDir, 'AboutA.json'), 'utf-8')),
		AboutB: JSON.parse(fs.readFileSync(path.join(contentDir, 'AboutB.json'), 'utf-8')),
		AboutC: JSON.parse(fs.readFileSync(path.join(contentDir, 'AboutC.json'), 'utf-8')),
		Header: JSON.parse(fs.readFileSync(path.join(contentDir, 'Header.json'), 'utf-8')),
		Footer: JSON.parse(fs.readFileSync(path.join(contentDir, 'Footer.json'), 'utf-8'))
			}
		};
	} catch (error) {
		console.error('Error loading content:', error);
		return { content: {} };
	}
}
