import fs from 'fs';
import path from 'path';

// Auto-generated by extract-content.js
// Components: HomeA, HomeB, HomeC, HomeD, HomeE, HomeF, HomeG, HomeH, HomeI, HomeL, Header, Footer

export async function load() {
	const contentDir = path.join(process.cwd(), 'static', 'content');

	try {
		return {
			content: {
		HomeA: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeA.json'), 'utf-8')),
		HomeB: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeB.json'), 'utf-8')),
		HomeC: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeC.json'), 'utf-8')),
		HomeD: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeD.json'), 'utf-8')),
		HomeE: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeE.json'), 'utf-8')),
		HomeF: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeF.json'), 'utf-8')),
		HomeG: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeG.json'), 'utf-8')),
		HomeH: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeH.json'), 'utf-8')),
		HomeI: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeI.json'), 'utf-8')),
		HomeL: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeL.json'), 'utf-8')),
		Header: JSON.parse(fs.readFileSync(path.join(contentDir, 'Header.json'), 'utf-8')),
		Footer: JSON.parse(fs.readFileSync(path.join(contentDir, 'Footer.json'), 'utf-8'))
			}
		};
	} catch (error) {
		console.error('Error loading content:', error);
		return { content: {} };
	}
}
