import fs from 'fs';
import path from 'path';

// Auto-generated by extract-content.js
// Components: ServiceOneA, ServiceOneB, ServiceOneC, ServiceOneD, ServiceOneE, ServiceOneF, Header, Footer

export async function load() {
	const contentDir = path.join(process.cwd(), 'static', 'content');

	try {
		return {
			content: {
		ServiceOneA: JSON.parse(fs.readFileSync(path.join(contentDir, 'ServiceOneA.json'), 'utf-8')),
		ServiceOneB: JSON.parse(fs.readFileSync(path.join(contentDir, 'ServiceOneB.json'), 'utf-8')),
		ServiceOneC: JSON.parse(fs.readFileSync(path.join(contentDir, 'ServiceOneC.json'), 'utf-8')),
		ServiceOneD: JSON.parse(fs.readFileSync(path.join(contentDir, 'ServiceOneD.json'), 'utf-8')),
		ServiceOneE: JSON.parse(fs.readFileSync(path.join(contentDir, 'ServiceOneE.json'), 'utf-8')),
		ServiceOneF: JSON.parse(fs.readFileSync(path.join(contentDir, 'ServiceOneF.json'), 'utf-8')),
		Header: JSON.parse(fs.readFileSync(path.join(contentDir, 'Header.json'), 'utf-8')),
		Footer: JSON.parse(fs.readFileSync(path.join(contentDir, 'Footer.json'), 'utf-8'))
			}
		};
	} catch (error) {
		console.error('Error loading content:', error);
		return { content: {} };
	}
}
