import fs from 'fs';
import path from 'path';

// Auto-generated by extract-content.js
// Components: ContactA, ContactB, Header, Footer

export async function load() {
	const contentDir = path.join(process.cwd(), 'static', 'content');

	try {
		return {
			content: {
		ContactA: JSON.parse(fs.readFileSync(path.join(contentDir, 'ContactA.json'), 'utf-8')),
		ContactB: JSON.parse(fs.readFileSync(path.join(contentDir, 'ContactB.json'), 'utf-8')),
		Header: JSON.parse(fs.readFileSync(path.join(contentDir, 'Header.json'), 'utf-8')),
		Footer: JSON.parse(fs.readFileSync(path.join(contentDir, 'Footer.json'), 'utf-8'))
			}
		};
	} catch (error) {
		console.error('Error loading content:', error);
		return { content: {} };
	}
}
