import fs from 'fs';
import path from 'path';

// Auto-generated by extract-content.js
// Components: TeamA, TeamB, TeamC, TeamD, Header, Footer

export async function load() {
	const contentDir = path.join(process.cwd(), 'static', 'content');

	try {
		return {
			content: {
		TeamA: JSON.parse(fs.readFileSync(path.join(contentDir, 'TeamA.json'), 'utf-8')),
		TeamB: JSON.parse(fs.readFileSync(path.join(contentDir, 'TeamB.json'), 'utf-8')),
		TeamC: JSON.parse(fs.readFileSync(path.join(contentDir, 'TeamC.json'), 'utf-8')),
		TeamD: JSON.parse(fs.readFileSync(path.join(contentDir, 'TeamD.json'), 'utf-8')),
		Header: JSON.parse(fs.readFileSync(path.join(contentDir, 'Header.json'), 'utf-8')),
		Footer: JSON.parse(fs.readFileSync(path.join(contentDir, 'Footer.json'), 'utf-8'))
			}
		};
	} catch (error) {
		console.error('Error loading content:', error);
		return { content: {} };
	}
}
