import fs from 'fs';
import path from 'path';

// Auto-generated by extract-content.js
// Components: HomeTwoA, HomeTwoB, HomeTwoC, HomeTwoD, HomeTwoE, HomeTwoF, HomeTwoG, HomeTwoH, HomeTwoI, HomeTwoJ, Header, Footer

export async function load() {
	const contentDir = path.join(process.cwd(), 'static', 'content');

	try {
		return {
			content: {
		HomeTwoA: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeTwoA.json'), 'utf-8')),
		HomeTwoB: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeTwoB.json'), 'utf-8')),
		HomeTwoC: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeTwoC.json'), 'utf-8')),
		HomeTwoD: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeTwoD.json'), 'utf-8')),
		HomeTwoE: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeTwoE.json'), 'utf-8')),
		HomeTwoF: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeTwoF.json'), 'utf-8')),
		HomeTwoG: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeTwoG.json'), 'utf-8')),
		HomeTwoH: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeTwoH.json'), 'utf-8')),
		HomeTwoI: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeTwoI.json'), 'utf-8')),
		HomeTwoJ: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeTwoJ.json'), 'utf-8')),
		Header: JSON.parse(fs.readFileSync(path.join(contentDir, 'Header.json'), 'utf-8')),
		Footer: JSON.parse(fs.readFileSync(path.join(contentDir, 'Footer.json'), 'utf-8'))
			}
		};
	} catch (error) {
		console.error('Error loading content:', error);
		return { content: {} };
	}
}
