import fs from 'fs';
import path from 'path';

// Auto-generated by extract-content.js
// Components: ServiceTwoA, ServiceTwoB, ServiceTwoC, ServiceTwoD, Header, Footer

export async function load() {
	const contentDir = path.join(process.cwd(), 'static', 'content');

	try {
		return {
			content: {
		ServiceTwoA: JSON.parse(fs.readFileSync(path.join(contentDir, 'ServiceTwoA.json'), 'utf-8')),
		ServiceTwoB: JSON.parse(fs.readFileSync(path.join(contentDir, 'ServiceTwoB.json'), 'utf-8')),
		ServiceTwoC: JSON.parse(fs.readFileSync(path.join(contentDir, 'ServiceTwoC.json'), 'utf-8')),
		ServiceTwoD: JSON.parse(fs.readFileSync(path.join(contentDir, 'ServiceTwoD.json'), 'utf-8')),
		Header: JSON.parse(fs.readFileSync(path.join(contentDir, 'Header.json'), 'utf-8')),
		Footer: JSON.parse(fs.readFileSync(path.join(contentDir, 'Footer.json'), 'utf-8'))
			}
		};
	} catch (error) {
		console.error('Error loading content:', error);
		return { content: {} };
	}
}
