import fs from 'fs';
import path from 'path';

// Auto-generated by extract-content.js
// Components: HomeOneA, HomeOneB, HomeOneC, HomeOneD, HomeOneE, HomeOneF, HomeOneG, HomeOneH, Header, Footer

export async function load() {
	const contentDir = path.join(process.cwd(), 'static', 'content');

	try {
		return {
			content: {
		HomeOneA: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeOneA.json'), 'utf-8')),
		HomeOneB: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeOneB.json'), 'utf-8')),
		HomeOneC: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeOneC.json'), 'utf-8')),
		HomeOneD: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeOneD.json'), 'utf-8')),
		HomeOneE: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeOneE.json'), 'utf-8')),
		HomeOneF: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeOneF.json'), 'utf-8')),
		HomeOneG: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeOneG.json'), 'utf-8')),
		HomeOneH: JSON.parse(fs.readFileSync(path.join(contentDir, 'HomeOneH.json'), 'utf-8')),
		Header: JSON.parse(fs.readFileSync(path.join(contentDir, 'Header.json'), 'utf-8')),
		Footer: JSON.parse(fs.readFileSync(path.join(contentDir, 'Footer.json'), 'utf-8'))
			}
		};
	} catch (error) {
		console.error('Error loading content:', error);
		return { content: {} };
	}
}
